# Generated by Django 5.2.17 on 2026-09-27 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_listings_it_status_7dd8d1_idx_listings_it_status_480edd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='地点名称')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='楼栋 / 校区')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='详细位置')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='地点说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '校园地点',
                'verbose_name_plural': '校园地点',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='listings.campuslocation', verbose_name='交易地点'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['location', 'status'], name='listings_it_locatio_3a2764_idx'),
        ),
    ]
