# Generated by Django 5.2.17 on 2026-09-27 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_campuslocation_item_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', '疑似诈骗或虚假信息'), ('spam', '重复发布或广告引流'), ('inappropriate', '不当内容'), ('other', '其他问题')], max_length=30, verbose_name='举报原因')),
                ('detail', models.TextField(blank=True, verbose_name='补充说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('resolved', '已处理'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.item', verbose_name='被举报商品')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '商品举报',
                'verbose_name_plural': '商品举报',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='listings_re_status_59ed6f_idx'), models.Index(fields=['item', 'status'], name='listings_re_item_id_32ae66_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'reporter'), name='unique_item_reporter')],
            },
        ),
    ]
