# Generated by Django 5.2.17 on 2026-09-27 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价格')),
                ('buyer_note', models.TextField(blank=True, verbose_name='买家备注')),
                ('status', models.CharField(choices=[('pending', '待卖家确认'), ('confirmed', '卖家已确认'), ('meeting', '待当面交付'), ('completed', '交易完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_orders', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='listings.item', verbose_name='商品')),
                ('meeting_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='listings.campuslocation', verbose_name='交付地点')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '交易订单',
                'verbose_name_plural': '交易订单',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', 'status'], name='listings_or_buyer_i_546650_idx'), models.Index(fields=['seller', 'status'], name='listings_or_seller__b7fa8c_idx')],
            },
        ),
    ]
