# Generated by Django 5.2.17 on 2026-09-27 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=1, verbose_name='浏览次数')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='首次浏览时间')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='最近浏览时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='listings.item', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'ordering': ['-last_viewed_at'],
                'indexes': [models.Index(fields=['user', '-last_viewed_at'], name='listings_br_user_id_7dca54_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='unique_user_browsing_item')],
            },
        ),
    ]
