# Generated by Django 5.2.17 on 2026-09-27 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_browsinghistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1 星'), (2, '2 星'), (3, '3 星'), (4, '4 星'), (5, '5 星')], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='listings.order', verbose_name='订单')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL, verbose_name='被评价人')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
            ],
            options={
                'verbose_name': '交易评价',
                'verbose_name_plural': '交易评价',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ratee', '-created_at'], name='listings_ra_ratee_i_241059_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'rater'), name='unique_order_rater')],
            },
        ),
    ]
