# Generated by Django 5.2.17 on 2026-09-27 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='目标状态')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='事件说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='listings.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单状态记录',
                'verbose_name_plural': '订单状态记录',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='listings_or_order_i_46ceff_idx')],
            },
        ),
    ]
