# Generated by Django 5.2.17 on 2026-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_orderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='to_status',
            field=models.CharField(choices=[('pending', '待卖家确认'), ('confirmed', '卖家已确认'), ('meeting', '待当面交付'), ('completed', '交易完成'), ('cancelled', '已取消')], max_length=20, verbose_name='目标状态'),
        ),
    ]
