# Generated by Django 5.2.17 on 2026-09-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=120, verbose_name='搜索词')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低价格')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高价格')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='结果数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to='listings.category', verbose_name='分类')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to='listings.campuslocation', verbose_name='交易地点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搜索记录',
                'verbose_name_plural': '搜索记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', '-created_at'], name='listings_se_query_792040_idx'), models.Index(fields=['user', '-created_at'], name='listings_se_user_id_81e930_idx')],
            },
        ),
    ]
