# Generated by Django 5.2.17 on 2026-09-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='condition',
            field=models.CharField(blank=True, max_length=120, verbose_name='成色筛选'),
        ),
    ]
