# Generated by Django 5.2.17 on 2026-09-27 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_searchquery_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='关注名称')),
                ('query', models.CharField(blank=True, max_length=120, verbose_name='搜索词')),
                ('condition', models.CharField(blank=True, max_length=120, verbose_name='成色筛选')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低价格')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高价格')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to='listings.category', verbose_name='分类')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to='listings.campuslocation', verbose_name='交易地点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注的搜索',
                'verbose_name_plural': '关注的搜索',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', '-created_at'], name='listings_sa_user_id_ec436e_idx'), models.Index(fields=['category', 'location', 'is_active'], name='listings_sa_categor_98877e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_user_saved_search_name')],
            },
        ),
    ]
