# Generated by Django 5.2.17 on 2026-09-27 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_notification_kind_savedsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('order_dispute', '交易争议更新')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='买家确认时间')),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='卖家确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmation', to='listings.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '交付确认',
                'verbose_name_plural': '交付确认',
            },
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_received', '未收到商品'), ('mismatch', '商品与描述不符'), ('payment', '价格或付款问题'), ('safety', '交易安全问题'), ('other', '其他争议')], max_length=30, verbose_name='争议类型')),
                ('detail', models.TextField(verbose_name='争议说明')),
                ('status', models.CharField(choices=[('open', '待处理'), ('reviewing', '处理中'), ('resolved', '已解决'), ('rejected', '已驳回')], default='open', max_length=20, verbose_name='处理状态')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理意见')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_order_disputes', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='listings.order', verbose_name='相关订单')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_order_disputes', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '交易争议',
                'verbose_name_plural': '交易争议',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='listings_or_status_1433dc_idx'), models.Index(fields=['opened_by', '-created_at'], name='listings_or_opened__29362b_idx')],
            },
        ),
    ]
