# Generated by Django 5.2.17 on 2026-09-27 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_notification_kind_deliveryconfirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('interested', '想看看'), ('dismiss', '不感兴趣')], max_length=20, verbose_name='反馈动作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次反馈时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近反馈时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to='listings.item', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '推荐反馈',
                'verbose_name_plural': '推荐反馈',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'action', '-updated_at'], name='listings_re_user_id_936981_idx'), models.Index(fields=['item', 'action'], name='listings_re_item_id_4bb55c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='unique_recommendation_feedback')],
            },
        ),
    ]
