# Generated by Django 5.2.17 on 2026-09-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_report_reviewed_at_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='卖家确认截止时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认提醒发送时间'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('order_dispute', '交易争议更新'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新')], max_length=30, verbose_name='通知类型'),
        ),
    ]
