# Generated by Django 5.2.17 on 2026-09-27 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_order_confirmation_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created', models.BooleanField(default=True, help_text='有人预约你的商品时提醒。', verbose_name='新的交易预约')),
                ('order_status', models.BooleanField(default=True, help_text='订单状态推进、取消或完成时提醒。', verbose_name='订单状态更新')),
                ('rating_received', models.BooleanField(default=True, help_text='交易对方完成评价时提醒。', verbose_name='收到交易评价')),
                ('message_received', models.BooleanField(default=True, help_text='收到新的私信时提醒。', verbose_name='收到新私信')),
                ('comment_received', models.BooleanField(default=True, help_text='有人在你的商品下留言时提醒。', verbose_name='收到商品留言')),
                ('saved_search_match', models.BooleanField(default=True, help_text='关注的搜索匹配到新商品时提醒。', verbose_name='关注的搜索有新商品')),
                ('order_dispute', models.BooleanField(default=True, help_text='交易争议状态发生变化时提醒。', verbose_name='交易争议更新')),
                ('order_expiring', models.BooleanField(default=True, help_text='交易预约接近确认截止时间时提醒。', verbose_name='交易预约即将超时')),
                ('order_expired', models.BooleanField(default=True, help_text='交易预约因超时被释放时提醒。', verbose_name='交易预约已超时')),
                ('report_update', models.BooleanField(default=True, help_text='你提交的举报有处理进展时提醒。', verbose_name='举报处理更新')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知偏好',
                'verbose_name_plural': '通知偏好',
            },
        ),
    ]
