# Generated by Django 5.2.17 on 2026-09-28 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='item_available',
            field=models.BooleanField(default=True, help_text='你关注的商品恢复为在售时提醒。', verbose_name='商品重新有货'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('order_dispute', '交易争议更新'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='ItemAvailabilityWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_watches', to='listings.item', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_availability_watches', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品有货提醒',
                'verbose_name_plural': '商品有货提醒',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', '-created_at'], name='listings_it_item_id_0ae2de_idx'), models.Index(fields=['user', '-created_at'], name='listings_it_user_id_bce838_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='unique_user_item_availability_watch')],
            },
        ),
    ]
