# Generated by Django 5.2.17 on 2026-09-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_notificationpreference_item_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='moderation_update',
            field=models.BooleanField(default=True, help_text='你提交的留言或私信完成复核时提醒。', verbose_name='内容审核结果'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('order_dispute', '交易争议更新'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果')], max_length=30, verbose_name='通知类型'),
        ),
    ]
