# Generated by Django 5.2.17 on 2026-09-28 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_notificationpreference_moderation_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='聚合键'),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近发生时间'),
        ),
        migrations.AddField(
            model_name='notification',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1, verbose_name='聚合次数'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'kind', 'dedupe_key', 'is_read'], name='listings_no_recipie_c557b3_idx'),
        ),
    ]
