# Generated by Django 5.2.17 on 2026-09-28 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_searchclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='结果位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='曝光时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_impressions', to='listings.item', verbose_name='商品')),
                ('search_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to='listings.searchquery', verbose_name='搜索记录')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_impressions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搜索曝光',
                'verbose_name_plural': '搜索曝光',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search_query', '-created_at'], name='listings_se_search__44d4d3_idx'), models.Index(fields=['item', '-created_at'], name='listings_se_item_id_5da9b8_idx'), models.Index(fields=['created_at'], name='listings_se_created_278b17_idx')],
            },
        ),
    ]
