# Generated by Django 5.2.17 on 2026-09-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_searchimpression'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120, verbose_name='主关键词')),
                ('synonym', models.CharField(max_length=120, verbose_name='同义词')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '搜索同义词',
                'verbose_name_plural': '搜索同义词',
                'ordering': ['keyword', 'synonym'],
                'indexes': [models.Index(fields=['keyword', 'is_active'], name='listings_se_keyword_f453e6_idx'), models.Index(fields=['synonym', 'is_active'], name='listings_se_synonym_a6c66d_idx')],
                'constraints': [models.UniqueConstraint(fields=('keyword', 'synonym'), name='unique_search_synonym_pair')],
            },
        ),
    ]
