# Generated by Django 5.2.17 on 2026-09-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_searchsynonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='operations_digest',
            field=models.BooleanField(default=True, help_text='管理员运营看板出现高优先级信号时发送每日摘要。', verbose_name='运营告警日报'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('order_dispute', '交易争议更新'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报')], max_length=30, verbose_name='通知类型'),
        ),
    ]
