# Generated by Django 5.2.17 on 2026-09-28 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_notificationpreference_operations_digest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='求购标题')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低预算')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高预算')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='需求截止时间')),
                ('status', models.CharField(choices=[('active', '寻找中'), ('fulfilled', '已找到'), ('closed', '已关闭'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_posts', to='listings.category', verbose_name='分类')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_posts', to='listings.campuslocation', verbose_name='期望地点')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_posts', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '求购信息',
                'verbose_name_plural': '求购信息',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='listings_de_status_8e27ad_idx'), models.Index(fields=['category', 'status'], name='listings_de_categor_ab663b_idx'), models.Index(fields=['location', 'status'], name='listings_de_locatio_385211_idx'), models.Index(fields=['expires_at', 'status'], name='listings_de_expires_b00a51_idx')],
            },
        ),
    ]
