# Generated by Django 5.2.17 on 2026-09-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_demandpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='listings.demandpost', verbose_name='相关求购'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='demand_match',
            field=models.BooleanField(default=True, help_text='有商品可能符合你发布的求购信息时提醒。', verbose_name='求购匹配提醒'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('order_dispute', '交易争议更新'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒')], max_length=30, verbose_name='通知类型'),
        ),
    ]
