# Generated by Django 5.2.17 on 2026-09-28 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_求购匹配通知'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待对方确认'), ('confirmed', '已确认'), ('declined', '对方未接受'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='安排状态')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回应时间')),
                ('decline_reason', models.CharField(blank=True, max_length=200, verbose_name='未接受原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_appointments', to='listings.campuslocation', verbose_name='交付地点')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='listings.order', verbose_name='订单')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_appointments', to=settings.AUTH_USER_MODEL, verbose_name='提议人')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_appointments', to=settings.AUTH_USER_MODEL, verbose_name='回应人')),
            ],
            options={
                'verbose_name': '交付时间安排',
                'verbose_name_plural': '交付时间安排',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['status', 'start_at'], name='listings_me_status_5274b0_idx'), models.Index(fields=['proposed_by', '-created_at'], name='listings_me_propose_5a7c93_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='meeting_appointment_end_after_start')],
            },
        ),
    ]
