# Generated by Django 5.2.17 on 2026-09-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_meetingappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='handoff_code_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='交付确认码错误次数'),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='handoff_code_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='交付确认码哈希'),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='handoff_code_hint',
            field=models.CharField(blank=True, max_length=8, verbose_name='交付确认码提示'),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='handoff_code_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交付确认码生成时间'),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='handoff_code_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交付确认码使用时间'),
        ),
    ]
