# Generated by Django 5.2.17 on 2026-09-28 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_deliveryconfirmation_handoff_code_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingappointment',
            name='buyer_arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='买家到场时间'),
        ),
        migrations.AddField(
            model_name='meetingappointment',
            name='seller_arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='卖家到场时间'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='meeting_incident',
            field=models.BooleanField(default=True, help_text='交付预约出现到场或安全异常时提醒。', verbose_name='交付预约异常'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('order_dispute', '交易争议更新'), ('meeting_incident', '交付预约异常'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='MeetingIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_show', '对方未到场'), ('late', '对方严重迟到'), ('safety', '现场安全问题'), ('other', '其他预约异常')], max_length=20, verbose_name='异常类型')),
                ('detail', models.TextField(verbose_name='情况说明')),
                ('status', models.CharField(choices=[('open', '待处理'), ('reviewing', '处理中'), ('resolved', '已确认异常'), ('dismissed', '已驳回')], default='open', max_length=20, verbose_name='处理状态')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('accused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused_meeting_incidents', to=settings.AUTH_USER_MODEL, verbose_name='相关对方')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='listings.meetingappointment', verbose_name='交付安排')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_meeting_incidents', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meeting_incidents', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '交付预约异常',
                'verbose_name_plural': '交付预约异常',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='listings_me_status_3149d9_idx'), models.Index(fields=['reported_by', '-created_at'], name='listings_me_reporte_298856_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reported_by', models.F('accused')), _negated=True), name='meeting_incident_reporter_differs_accused')],
            },
        ),
    ]
