# Generated by Django 5.2.17 on 2026-09-28 18:12

import django.db.models.deletion
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_meetingappointment_buyer_arrived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='dispute_evidence/%Y/%m/', validators=[listings.models.validate_dispute_evidence], verbose_name='证据文件')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='证据说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='listings.orderdispute', verbose_name='交易争议')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_order_dispute_evidence', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '交易争议证据',
                'verbose_name_plural': '交易争议证据',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dispute', '-created_at'], name='listings_or_dispute_3bf31a_idx')],
            },
        ),
    ]
