# Generated by Django 5.2.17 on 2026-09-28 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_增加交易争议证据'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='可选。到期后商品会自动下架；不填写表示长期展示。', null=True, verbose_name='展示截止时间'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='item_expired',
            field=models.BooleanField(default=True, help_text='你发布的商品自动下架时提醒。', verbose_name='商品展示已到期'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', '在售'), ('reserved', '已预订'), ('sold', '已售出'), ('expired', '已过期')], default='available', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('item_expired', '商品展示已到期'), ('order_dispute', '交易争议更新'), ('meeting_incident', '交付预约异常'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'expires_at'], name='listings_it_status_e5b7cb_idx'),
        ),
    ]
