# Generated by Django 5.2.17 on 2026-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_item_expires_at_notificationpreference_item_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trade_mode',
            field=models.CharField(choices=[('sale', '出售'), ('free', '免费赠送')], default='sale', max_length=20, verbose_name='交易方式'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格'),
        ),
    ]
