# Generated by Django 5.2.17 on 2026-09-28 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_item_trade_mode_alter_item_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='gift_application',
            field=models.BooleanField(default=True, help_text='有人申请领取你的免费商品时提醒。', verbose_name='新的领取申请'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='gift_application_status',
            field=models.BooleanField(default=True, help_text='免费领取申请被选中、未选中或撤回时提醒。', verbose_name='领取申请状态更新'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('gift_application', '新的领取申请'), ('gift_application_status', '领取申请状态更新'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('item_expired', '商品展示已到期'), ('order_dispute', '交易争议更新'), ('meeting_incident', '交付预约异常'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='GiftApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_note', models.TextField(blank=True, verbose_name='申请说明')),
                ('status', models.CharField(choices=[('pending', '等待选择'), ('selected', '已选中'), ('rejected', '未选中'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='申请状态')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_applications', to='listings.item', verbose_name='商品')),
                ('meeting_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_applications', to='listings.campuslocation', verbose_name='领取地点')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_application', to='listings.order', verbose_name='生成订单')),
            ],
            options={
                'verbose_name': '免费领取申请',
                'verbose_name_plural': '免费领取申请',
                'ordering': ['status', 'created_at'],
                'indexes': [models.Index(fields=['item', 'status', 'created_at'], name='listings_gi_item_id_5167fc_idx'), models.Index(fields=['applicant', 'status', '-created_at'], name='listings_gi_applica_4380a2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('item', 'applicant'), name='unique_pending_gift_application')],
            },
        ),
    ]
