# Generated by Django 5.2.17 on 2026-09-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_notificationpreference_gift_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='buyer_returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='买家归还登记时间'),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='seller_returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='卖家归还确认时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='borrow_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='仅限期借用使用，范围为 1 至 90 天。', verbose_name='默认借用天数'),
        ),
        migrations.AddField(
            model_name='item',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='仅限期借用使用，归还确认后由双方线下处理押金。', max_digits=10, verbose_name='借用押金'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='借用押金'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计归还时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间'),
        ),
        migrations.AlterField(
            model_name='item',
            name='trade_mode',
            field=models.CharField(choices=[('sale', '出售'), ('free', '免费赠送'), ('borrow', '限期借用')], default='sale', max_length=20, verbose_name='交易方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待卖家确认'), ('confirmed', '卖家已确认'), ('meeting', '待当面交付'), ('completed', '交易完成'), ('cancelled', '已取消'), ('borrowed', '借用中'), ('returned', '已归还')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='to_status',
            field=models.CharField(choices=[('pending', '待卖家确认'), ('confirmed', '卖家已确认'), ('meeting', '待当面交付'), ('completed', '交易完成'), ('cancelled', '已取消'), ('borrowed', '借用中'), ('returned', '已归还')], max_length=20, verbose_name='目标状态'),
        ),
    ]
