# Generated by Django 5.2.17 on 2026-09-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_deliveryconfirmation_buyer_returned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_overdue_notice_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还逾期提醒发送时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还提醒发送时间'),
        ),
    ]
