# Generated by Django 5.2.17 on 2026-09-28 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_alter_order_item_order_unique_active_order_per_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='demand_response',
            field=models.BooleanField(default=True, help_text='有人响应你的求购，或你的响应状态发生变化时提醒。', verbose_name='求购响应更新'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('gift_application', '新的领取申请'), ('gift_application_status', '领取申请状态更新'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('item_expired', '商品展示已到期'), ('order_dispute', '交易争议更新'), ('meeting_incident', '交付预约异常'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒'), ('demand_response', '求购响应更新')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='DemandResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='响应说明')),
                ('match_score', models.PositiveSmallIntegerField(default=0, verbose_name='匹配分数')),
                ('match_reason', models.CharField(blank=True, max_length=200, verbose_name='匹配依据')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已确认匹配'), ('rejected', '未采纳'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='响应状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='响应时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='listings.demandpost', verbose_name='求购信息')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_responses', to='listings.item', verbose_name='响应商品')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_responses', to=settings.AUTH_USER_MODEL, verbose_name='响应人')),
            ],
            options={
                'verbose_name': '求购响应',
                'verbose_name_plural': '求购响应',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['demand', 'status', '-created_at'], name='listings_de_demand__72d328_idx'), models.Index(fields=['responder', 'status', '-created_at'], name='listings_de_respond_fe10ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('demand', 'item'), name='unique_demand_response_item')],
            },
        ),
    ]
