# Generated by Django 5.2.17 on 2026-09-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_notificationpreference_demand_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuslocation',
            name='is_public',
            field=models.BooleanField(default=True, help_text='用于交付推荐与安全提示。建议将图书馆大厅、门卫室等人流较多区域标记为公共区域。', verbose_name='公共交付区域'),
        ),
        migrations.AddField(
            model_name='campuslocation',
            name='safety_note',
            field=models.CharField(blank=True, help_text='可填写该地点的开放时间、照明或门禁等注意事项。', max_length=200, verbose_name='安全提示'),
        ),
    ]
