# Generated by Django 5.2.17 on 2026-09-28 22:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_campuslocation_is_public_campuslocation_safety_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='专题名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='专题标识')),
                ('description', models.TextField(blank=True, verbose_name='专题说明')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '校园专题',
                'verbose_name_plural': '校园专题',
                'ordering': ['-starts_at', 'title'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='listings_ca_is_acti_e74e14_idx')],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='listings.campuscampaign', verbose_name='校园专题'),
        ),
    ]
