# Generated by Django 5.2.17 on 2026-09-28 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_campuscampaign_item_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='lost_found_lead',
            field=models.BooleanField(default=True, help_text='有人提交、确认或拒绝失物招领线索时提醒。', verbose_name='失物招领线索更新'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='lost_found_match',
            field=models.BooleanField(default=True, help_text='有记录与我发布的失物招领信息可能匹配时提醒。', verbose_name='失物招领匹配提醒'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('gift_application', '新的领取申请'), ('gift_application_status', '领取申请状态更新'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('item_expired', '商品展示已到期'), ('order_dispute', '交易争议更新'), ('meeting_incident', '交付预约异常'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒'), ('demand_response', '求购响应更新'), ('lost_found_match', '失物招领匹配提醒'), ('lost_found_lead', '失物招领线索更新')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='LostFoundPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('lost', '我丢失了'), ('found', '我捡到了')], max_length=10, verbose_name='记录类型')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='信息截止时间')),
                ('identifying_features', models.CharField(blank=True, help_text='建议填写颜色、品牌、贴纸、挂件等不宜公开过度暴露的特征。', max_length=240, verbose_name='颜色与辨识特征')),
                ('status', models.CharField(choices=[('active', '寻找中'), ('matched', '已匹配'), ('closed', '已关闭'), ('expired', '已过期')], default='active', max_length=12, verbose_name='状态')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_posts', to='listings.category', verbose_name='物品分类')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_posts', to='listings.campuslocation', verbose_name='发生地点')),
                ('matched_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by_posts', to='listings.lostfoundpost', verbose_name='匹配记录')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_posts', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '失物招领记录',
                'verbose_name_plural': '失物招领记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostFoundLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='线索说明')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已确认'), ('rejected', '暂不匹配'), ('withdrawn', '已撤回')], default='pending', max_length=12, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_leads', to=settings.AUTH_USER_MODEL, verbose_name='线索提供者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='listings.lostfoundpost', verbose_name='失物招领记录')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_leads', to='listings.lostfoundpost', verbose_name='关联记录')),
            ],
            options={
                'verbose_name': '失物招领线索',
                'verbose_name_plural': '失物招领线索',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lostfoundpost',
            index=models.Index(fields=['status', 'post_type', '-created_at'], name='listings_lo_status_384238_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundpost',
            index=models.Index(fields=['category', 'status'], name='listings_lo_categor_0132c9_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundpost',
            index=models.Index(fields=['location', 'status'], name='listings_lo_locatio_0e827d_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundpost',
            index=models.Index(fields=['occurred_at', 'status'], name='listings_lo_occurre_9633dd_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundpost',
            index=models.Index(fields=['expires_at', 'status'], name='listings_lo_expires_203dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundlead',
            index=models.Index(fields=['post', 'status', '-created_at'], name='listings_lo_post_id_d50e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundlead',
            index=models.Index(fields=['respondent', 'status', '-created_at'], name='listings_lo_respond_203cba_idx'),
        ),
        migrations.AddConstraint(
            model_name='lostfoundlead',
            constraint=models.UniqueConstraint(fields=('post', 'respondent'), name='unique_lost_found_lead_by_user'),
        ),
    ]
