# Generated by Django 5.2.17 on 2026-09-29 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_notificationpreference_lost_found_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandOpportunityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radar_key', models.CharField(max_length=260, verbose_name='雷达主题标识')),
                ('title', models.CharField(max_length=160, verbose_name='机会主题')),
                ('level', models.CharField(default='medium', max_length=20, verbose_name='优先级')),
                ('opportunity_score', models.PositiveIntegerField(default=0, verbose_name='机会分')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='无结果搜索次数')),
                ('demand_count', models.PositiveIntegerField(default=0, verbose_name='有效求购数')),
                ('available_supply', models.PositiveIntegerField(default=0, verbose_name='创建任务时供给数')),
                ('evidence', models.JSONField(blank=True, default=list, verbose_name='证据信号')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='建议动作')),
                ('status', models.CharField(choices=[('todo', '待跟进'), ('in_progress', '跟进中'), ('completed', '已完成'), ('ignored', '已忽略')], default='todo', max_length=20, verbose_name='任务状态')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='跟进截止时间')),
                ('note', models.TextField(blank=True, verbose_name='跟进备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demand_opportunity_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_opportunity_tasks', to='listings.category', verbose_name='分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demand_opportunity_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_opportunity_tasks', to='listings.campuslocation', verbose_name='地点')),
            ],
            options={
                'verbose_name': '需求机会跟进任务',
                'verbose_name_plural': '需求机会跟进任务',
                'ordering': ['status', '-opportunity_score', '-created_at'],
                'indexes': [models.Index(fields=['status', '-opportunity_score'], name='listings_de_status_7a4868_idx'), models.Index(fields=['radar_key', 'status'], name='listings_de_radar_k_c4ab9a_idx'), models.Index(fields=['assigned_to', 'status'], name='listings_de_assigne_892ad3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['todo', 'in_progress'])), fields=('radar_key',), name='unique_open_demand_opportunity_task')],
            },
        ),
    ]
