# Generated by Django 5.2.17 on 2026-09-29 01:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_demandopportunitytask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trade_completed', '完成交易'), ('borrow_returned', '完成借用归还'), ('gift_completed', '完成免费赠送'), ('lost_found_help', '协助失物招领'), ('demand_helped', '响应校园求购')], max_length=30, verbose_name='贡献类型')),
                ('points', models.PositiveIntegerField(verbose_name='贡献积分')),
                ('title', models.CharField(max_length=120, verbose_name='贡献标题')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='贡献说明')),
                ('source_key', models.CharField(help_text='同一业务事件只能产生一次贡献记录，避免重复积分。', max_length=180, unique=True, verbose_name='来源幂等键')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发生时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_contributions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '校园互助贡献',
                'verbose_name_plural': '校园互助贡献',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='listings_co_user_id_40c488_idx'), models.Index(fields=['user', 'kind', '-occurred_at'], name='listings_co_user_id_554497_idx')],
            },
        ),
    ]

