# Generated by Django 5.2.17 on 2026-09-29 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_communitycontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('demand', '校园求购'), ('lost_found', '失物招领')], max_length=20, verbose_name='机会类型')),
                ('expires_at', models.DateTimeField(verbose_name='忽略截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='忽略时间')),
                ('demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_dismissals', to='listings.demandpost', verbose_name='求购信息')),
                ('lost_found_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_dismissals', to='listings.lostfoundpost', verbose_name='失物招领记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_dismissals', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '互助机会忽略记录',
                'verbose_name_plural': '互助机会忽略记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='listings_op_user_id_dc8db5_idx'), models.Index(fields=['kind', 'expires_at'], name='listings_op_kind_d62b10_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('demand__isnull', False), ('kind', 'demand'), ('lost_found_post__isnull', True)), models.Q(('demand__isnull', True), ('kind', 'lost_found'), ('lost_found_post__isnull', False)), _connector='OR'), name='opportunity_dismissal_target_matches_kind'), models.UniqueConstraint(condition=models.Q(('demand__isnull', False)), fields=('user', 'demand'), name='unique_opportunity_dismissal_demand'), models.UniqueConstraint(condition=models.Q(('lost_found_post__isnull', False)), fields=('user', 'lost_found_post'), name='unique_opportunity_dismissal_lost_found')],
            },
        ),
    ]
