# Generated by Django 5.2.17 on 2026-09-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_暂停互助机会展示'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='opportunity_digest',
            field=models.BooleanField(default=True, help_text='定期汇总可能适合你响应的求购和失物招领机会。', verbose_name='互助机会摘要'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('gift_application', '新的领取申请'), ('gift_application_status', '领取申请状态更新'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('item_expired', '商品展示已到期'), ('order_dispute', '交易争议更新'), ('meeting_incident', '交付预约异常'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒'), ('demand_response', '求购响应更新'), ('lost_found_match', '失物招领匹配提醒'), ('lost_found_lead', '失物招领线索更新'), ('opportunity_digest', '互助机会摘要')], max_length=30, verbose_name='通知类型'),
        ),
    ]
