# Generated by Django 5.2.17 on 2026-09-29 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_增加互助机会摘要通知'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, help_text='在这个时间之前不计入未读提醒，适合暂时不方便处理的事项。', null=True, verbose_name='延后至'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'snoozed_until', '-created_at'], name='listings_no_recipie_2cdcc7_idx'),
        ),
    ]
