# Generated by Django 5.2.17 on 2026-09-29 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0047_增加通知延后处理'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, help_text='启用后，指定时段内不会显示顶部未读提醒，但通知仍会保留在通知中心。', verbose_name='启用免打扰时段'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='免打扰结束时间'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='免打扰开始时间'),
        ),
    ]
