# Generated by Django 5.2.17 on 2026-09-29 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_增加通知免打扰时段'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='mutual_aid_feedback',
            field=models.BooleanField(default=True, help_text='互助发布者确认响应结果后提醒参与者。', verbose_name='互助完成反馈'),
        ),
        migrations.AlterField(
            model_name='communitycontribution',
            name='kind',
            field=models.CharField(choices=[('trade_completed', '完成交易'), ('borrow_returned', '完成借用归还'), ('gift_completed', '完成免费赠送'), ('lost_found_help', '协助失物招领'), ('demand_helped', '响应校园求购'), ('mutual_aid_completed', '完成一次校园互助')], max_length=30, verbose_name='贡献类型'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('gift_application', '新的领取申请'), ('gift_application_status', '领取申请状态更新'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('item_expired', '商品展示已到期'), ('order_dispute', '交易争议更新'), ('meeting_incident', '交付预约异常'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒'), ('demand_response', '求购响应更新'), ('lost_found_match', '失物招领匹配提醒'), ('lost_found_lead', '失物招领线索更新'), ('opportunity_digest', '互助机会摘要'), ('mutual_aid_feedback', '互助完成反馈')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='MutualAidFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('completed', '已完成'), ('unresolved', '暂未解决')], max_length=20, verbose_name='互助结果')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='反馈标签')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('demand_response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='listings.demandresponse', verbose_name='求购响应')),
                ('lost_found_lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='listings.lostfoundlead', verbose_name='失物招领线索')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_mutual_aid_feedback', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
            ],
            options={
                'verbose_name': '互助完成反馈',
                'verbose_name_plural': '互助完成反馈',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submitted_by', '-created_at'], name='listings_mu_submitt_c62553_idx'), models.Index(fields=['outcome', '-created_at'], name='listings_mu_outcome_ce04bf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('demand_response__isnull', False), ('lost_found_lead__isnull', True)), models.Q(('demand_response__isnull', True), ('lost_found_lead__isnull', False)), _connector='OR'), name='mutual_aid_feedback_exactly_one_source')],
            },
        ),
    ]
