# Generated by Django 5.2.17 on 2026-09-29 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_notificationpreference_mutual_aid_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='分组名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_collections', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '心愿单分组',
                'verbose_name_plural': '心愿单分组',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='listings.favoritecollection', verbose_name='所属分组'),
        ),
        migrations.AddIndex(
            model_name='favoritecollection',
            index=models.Index(fields=['user', 'name'], name='listings_fa_user_id_36f9a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoritecollection',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_favorite_collection_name'),
        ),
    ]
