# Generated by Django 5.2.17 on 2026-10-09 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_favorite_collections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearchMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True, verbose_name='命中时间')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='已通知时间')),
            ],
            options={
                'verbose_name': '关注搜索命中缓冲',
                'verbose_name_plural': '关注搜索命中缓冲',
                'ordering': ['-matched_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='saved_search_digest',
            field=models.BooleanField(default=True, help_text='选择每日或每周汇总的关注搜索，会在对应周期发送一条合并提醒。', verbose_name='关注搜索汇总提醒'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='max_matches_per_notice',
            field=models.PositiveSmallIntegerField(default=3, help_text='一条通知里最多列出几条命中商品，避免一次刷屏。', verbose_name='单次最多提醒条数'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='notify_frequency',
            field=models.CharField(choices=[('instant', '即时提醒'), ('daily', '每日汇总'), ('weekly', '每周汇总')], default='instant', help_text='即时提醒在商品发布时马上通知；汇总方式按日或按周合并成一条提醒。', max_length=10, verbose_name='提醒频率'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='quiet_until',
            field=models.DateTimeField(blank=True, help_text='在这个时间之前不发送这条关注的提醒，适合考试周或假期。', null=True, verbose_name='临时静默至'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_created', '新的交易预约'), ('gift_application', '新的领取申请'), ('gift_application_status', '领取申请状态更新'), ('order_status', '订单状态更新'), ('rating_received', '收到交易评价'), ('message_received', '收到新私信'), ('comment_received', '收到商品留言'), ('saved_search_match', '关注的搜索有新商品'), ('item_available', '商品重新有货'), ('item_expired', '商品展示已到期'), ('order_dispute', '交易争议更新'), ('meeting_incident', '交付预约异常'), ('order_expiring', '交易预约即将超时'), ('order_expired', '交易预约已超时'), ('report_update', '举报处理更新'), ('moderation_update', '内容审核结果'), ('operations_digest', '运营告警日报'), ('demand_match', '求购匹配提醒'), ('demand_response', '求购响应更新'), ('lost_found_match', '失物招领匹配提醒'), ('lost_found_lead', '失物招领线索更新'), ('opportunity_digest', '互助机会摘要'), ('saved_search_digest', '关注搜索汇总提醒')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['notify_frequency', 'is_active'], name='listings_sa_notify__2f2fde_idx'),
        ),
        migrations.AddField(
            model_name='savedsearchmatch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_matches', to='listings.item', verbose_name='命中商品'),
        ),
        migrations.AddField(
            model_name='savedsearchmatch',
            name='saved_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffered_matches', to='listings.savedsearch', verbose_name='关注的搜索'),
        ),
        migrations.AddIndex(
            model_name='savedsearchmatch',
            index=models.Index(fields=['saved_search', 'notified_at', '-matched_at'], name='listings_sa_saved_s_486c36_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearchmatch',
            index=models.Index(fields=['item'], name='listings_sa_item_id_ef711a_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedsearchmatch',
            constraint=models.UniqueConstraint(fields=('saved_search', 'item'), name='unique_saved_search_item_match'),
        ),
    ]
