# Generated by Django 5.2.17 on 2026-10-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_savedsearchmatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='学期名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='学期标识')),
                ('kind', models.CharField(choices=[('spring', '春季学期'), ('autumn', '秋季学期'), ('summer', '夏学期'), ('winter', '冬学期')], default='autumn', max_length=10, verbose_name='学期类型')),
                ('starts_on', models.DateField(verbose_name='开始日期')),
                ('ends_on', models.DateField(verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, help_text='停用后该学期不再参与阶段计算，但历史数据保留。', verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学期日历',
                'verbose_name_plural': '学期日历',
                'ordering': ['-starts_on'],
                'indexes': [models.Index(fields=['is_active', 'starts_on'], name='listings_ac_is_acti_05db37_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('registration', '开学周'), ('regular', '常规教学周'), ('exam', '考试周'), ('graduation', '毕业季'), ('holiday', '假期')], default='regular', max_length=20, verbose_name='阶段')),
                ('start_offset', models.PositiveSmallIntegerField(default=0, help_text='以学期开始日期为第 0 天计算。', verbose_name='开始偏移（天）')),
                ('end_offset', models.PositiveSmallIntegerField(default=0, help_text='含末尾日期；超出学期长度时会被截断。', verbose_name='结束偏移（天）')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='阶段说明')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='listings.academicterm', verbose_name='所属学期')),
            ],
            options={
                'verbose_name': '学期阶段',
                'verbose_name_plural': '学期阶段',
                'ordering': ['term', 'start_offset'],
                'constraints': [models.UniqueConstraint(fields=('term', 'start_offset'), name='unique_term_phase_start_offset')],
            },
        ),
        migrations.CreateModel(
            name='AcademicTermSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_key', models.CharField(max_length=20, verbose_name='阶段')),
                ('phase_label', models.CharField(blank=True, max_length=40, verbose_name='阶段名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('day_count', models.PositiveSmallIntegerField(default=0, verbose_name='天数')),
                ('new_items', models.PositiveIntegerField(default=0, verbose_name='新增商品')),
                ('new_demands', models.PositiveIntegerField(default=0, verbose_name='新增求购')),
                ('new_orders', models.PositiveIntegerField(default=0, verbose_name='新增预约')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='完成交易')),
                ('new_searches', models.PositiveIntegerField(default=0, verbose_name='搜索次数')),
                ('zero_result_searches', models.PositiveIntegerField(default=0, verbose_name='无结果搜索')),
                ('refreshed_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='listings.academicterm', verbose_name='所属学期')),
            ],
            options={
                'verbose_name': '学期阶段统计',
                'verbose_name_plural': '学期阶段统计',
                'ordering': ['term', 'start_date'],
                'constraints': [models.UniqueConstraint(fields=('term', 'phase_key', 'start_date'), name='unique_term_phase_snapshot')],
            },
        ),
    ]
