# Generated by Django 5.2.17 on 2026-10-09 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0052_academicterm_academicphase_academictermsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='标记为已读的时间，用于统计各类通知的实际处理时效。', null=True, verbose_name='阅读时间'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'kind', 'is_read', 'read_at'], name='listings_no_recipie_9cfa92_idx'),
        ),
    ]
