# Generated by Django 5.2.17 on 2026-10-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0054_backfill_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attention_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='最近一次向卖家发送“关注放缓”建议提醒的时间，用于控制提醒频率。', null=True, verbose_name='关注放缓提醒时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, help_text='卖家主动刷新上架的时间；未刷新过时为空，按发布时间计算新鲜度。', null=True, verbose_name='最近刷新时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_drop_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='最近一次向卖家发送降价建议提醒的时间。', null=True, verbose_name='降价提醒时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='refresh_count',
            field=models.PositiveIntegerField(default=0, help_text='记录卖家主动刷新次数，用于避免频繁刷屏。', verbose_name='刷新次数'),
        ),
    ]
