# Generated by Django 5.2.17 on 2026-10-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0056_notificationpreference_lifecycle_reminder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='命令名称')),
                ('status', models.CharField(choices=[('succeeded', '成功'), ('failed', '失败')], max_length=16, verbose_name='运行状态')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(verbose_name='结束时间')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='运行指标')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '定时任务运行记录',
                'verbose_name_plural': '定时任务运行记录',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['name', '-started_at'], name='task_run_name_started_idx'), models.Index(fields=['-started_at'], name='task_run_started_idx')],
            },
        ),
    ]
