# Generated by Django 5.2.17 on 2026-10-09 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0057_taskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowReturnEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_level', models.PositiveSmallIntegerField(choices=[(0, '未升级'), (1, '已提醒借用方'), (2, '已通知双方'), (3, '已上报治理队列')], default=0, verbose_name='升级等级')),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='最近升级时间')),
                ('escalation_count', models.PositiveSmallIntegerField(default=0, verbose_name='累计升级次数')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='归还闭环时间')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='最近一次说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_escalation', to='listings.order', verbose_name='借用订单')),
            ],
            options={
                'verbose_name': '借用逾期催收',
                'verbose_name_plural': '借用逾期催收',
                'ordering': ['-last_escalated_at', '-id'],
                'indexes': [models.Index(fields=['escalation_level', 'last_escalated_at'], name='listings_bo_escalat_a76754_idx'), models.Index(fields=['resolved_at', 'escalation_level'], name='listings_bo_resolve_3b51cf_idx')],
            },
        ),
    ]
