# Generated by Django 5.2.17 on 2026-10-10 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0058_borrowreturnescalation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSynonymRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120, verbose_name='用户先搜')),
                ('target', models.CharField(max_length=120, verbose_name='随后改搜')),
                ('reason', models.CharField(choices=[('not_equivalent', '不是同一个东西'), ('too_rare', '出现次数太少，证据不足'), ('ambiguous', '词义有歧义，不宜扩大搜索范围')], max_length=20, verbose_name='否决原因')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='否决时间')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonym_rejections', to=settings.AUTH_USER_MODEL, verbose_name='否决人')),
            ],
            options={
                'verbose_name': '同义词候选否决',
                'verbose_name_plural': '同义词候选否决',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reason', '-created_at'], name='listings_se_reason_f1cd64_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_synonym_rejection_pair')],
            },
        ),
    ]
