# Generated by Django 5.2.17 on 2026-09-27 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
        ('listings', '0019_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['receiver', 'is_read', '-created_at'], name='pm_receiver_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['sender', 'receiver', '-created_at'], name='pm_sender_receiver_created_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['receiver', 'sender', '-created_at'], name='pm_receiver_sender_created_idx'),
        ),
    ]
