# Generated by Django 5.2.17 on 2026-09-28 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_privatemessage_pm_receiver_read_created_idx_and_more'),
        ('listings', '0020_notificationpreference_item_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('comment', '商品留言'), ('private_message', '私信')], max_length=30, verbose_name='内容渠道')),
                ('content', models.TextField(verbose_name='被拦截内容')),
                ('matched_terms', models.CharField(max_length=255, verbose_name='命中规则')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('confirmed', '确认违规'), ('dismissed', '误判放行')], default='pending', max_length=20, verbose_name='审核状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='拦截时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to=settings.AUTH_USER_MODEL, verbose_name='内容作者')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='listings.item', verbose_name='关联商品')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_moderation_events', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '内容审核记录',
                'verbose_name_plural': '内容审核记录',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='chat_messag_status_a15786_idx'), models.Index(fields=['channel', '-created_at'], name='chat_messag_channel_8045b8_idx'), models.Index(fields=['author', '-created_at'], name='chat_messag_author__fe6535_idx')],
            },
        ),
    ]
