# Generated by Django 5.2.17 on 2026-09-28 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_moderationevent'),
        ('listings', '0021_notificationpreference_moderation_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationevent',
            options={'ordering': ['status', '-risk_score', '-created_at'], 'verbose_name': '内容审核记录', 'verbose_name_plural': '内容审核记录'},
        ),
        migrations.RemoveIndex(
            model_name='moderationevent',
            name='chat_messag_status_a15786_idx',
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='risk_level',
            field=models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=10, verbose_name='风险等级'),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='风险分数'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['status', '-risk_score', '-created_at'], name='chat_messag_status_822cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['risk_level', 'status', '-created_at'], name='chat_messag_risk_le_7454ed_idx'),
        ),
    ]
