# Generated by Django 5.2.17 on 2026-09-28 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=120, unique=True, verbose_name='校园邮箱域名')),
                ('name', models.CharField(max_length=120, verbose_name='学校或组织名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '校园邮箱域名',
                'verbose_name_plural': '校园邮箱域名',
                'ordering': ['name', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='CampusVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_email', models.EmailField(max_length=254, unique=True, verbose_name='校园邮箱')),
                ('domain_name', models.CharField(blank=True, max_length=120, verbose_name='学校或组织名称')),
                ('status', models.CharField(choices=[('unverified', '未认证'), ('pending', '待验证邮箱'), ('verified', '已认证'), ('rejected', '已失效')], default='unverified', max_length=20, verbose_name='认证状态')),
                ('token_hash', models.CharField(blank=True, max_length=128, verbose_name='验证令牌哈希')),
                ('token_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='令牌生成时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='认证时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campus_verification', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '校园身份认证',
                'verbose_name_plural': '校园身份认证',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='accounts_ca_status_4bb5ae_idx'), models.Index(fields=['campus_email'], name='accounts_ca_campus__8c8cec_idx')],
            },
        ),
    ]
