from django.urls import path
from . import views

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('category/<int:category_id>/', views.item_list, name='item_list_by_category'),
    path('item/<int:item_id>/', views.item_detail, name='item_detail'),
    path('item/<int:item_id>/report/', views.report_item, name='report_item'),
    path('item/<int:item_id>/order/', views.create_order, name='create_order'),
    path('item/new/', views.new_item, name='new_item'),
    path('item/<int:item_id>/edit/', views.edit_item, name='edit_item'),
    path('item/<int:item_id>/delete/', views.delete_item, name='delete_item'),
    path('item/<int:item_id>/mark_sold/', views.mark_sold, name='mark_sold'),
    path('item/<int:item_id>/favorite/', views.toggle_favorite, name='toggle_favorite'),
    path('item/<int:item_id>/availability-watch/', views.toggle_availability_watch, name='toggle_availability_watch'),
    path('item/<int:item_id>/recommendation-feedback/', views.recommendation_feedback, name='recommendation_feedback'),
    path('favorites/', views.favorite_list, name='favorite_list'),
    path('orders/', views.my_orders, name='my_orders'),
    path('history/', views.browsing_history, name='browsing_history'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order/<int:order_id>/status/', views.update_order_status, name='update_order_status'),
    path('order/<int:order_id>/confirm-delivery/', views.confirm_delivery, name='confirm_delivery'),
    path('order/<int:order_id>/dispute/', views.open_dispute, name='open_dispute'),
    path('order/<int:order_id>/rate/', views.rate_order, name='rate_order'),
    path('my_items/', views.my_items, name='my_items'),
    path('search/', views.search_items, name='search_items'),
    path('search/suggestions/', views.search_suggestions, name='search_suggestions'),
    path('operations/', views.operations_dashboard, name='operations_dashboard'),
    path('operations/export/', views.operations_dashboard_export, name='operations_dashboard_export'),
    path('operations/search-insights/', views.search_insights, name='search_insights'),
    path('operations/search-insights/export/', views.search_insights_export, name='search_insights_export'),
    path('reports/', views.report_list, name='report_list'),
    path('reports/<int:report_id>/review/', views.review_report, name='review_report'),
    path('disputes/', views.dispute_list, name='dispute_list'),
    path('disputes/<int:dispute_id>/resolve/', views.resolve_dispute, name='resolve_dispute'),
    path('saved-searches/', views.saved_search_list, name='saved_search_list'),
    path('saved-searches/save/', views.save_search, name='save_search'),
    path('saved-searches/<int:saved_search_id>/toggle/', views.toggle_saved_search, name='toggle_saved_search'),
    path('saved-searches/<int:saved_search_id>/delete/', views.delete_saved_search, name='delete_saved_search'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/unread-summary/', views.unread_summary, name='unread_summary'),
    path('notifications/preferences/', views.notification_preferences, name='notification_preferences'),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/read-selected/', views.mark_selected_notifications_read, name='mark_selected_notifications_read'),
]
